version: '3.3'

services:
  db:
    restart: always
    container_name: django_db
    image: postgres
    env_file:
      - .env
    volumes:
      - /home/postgresql_db:/var/lib/postgresql/data:rw
  rest:
    restart: always
    container_name: django_drf
    image: django
    build:
      context: ./core/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - /home/rest:/home/abdullah
    ports:
      - "8866:8866"
    depends_on:
      - db
  
  frontend:
    restart: always
    command : npm start
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - rest
  